spring.application.name=connections-service

server.port=9030
server.servlet.context-path=/connections

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka



# Kafka Configuration

spring.kafka.consumer.group-id=connections-group-v1
spring.kafka.consumer.auto-offset-reset=latest

# Key & Error-Handling Value Deserializer Configuration
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate to JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Set Default Target Type for JSON Deserialization
spring.kafka.consumer.properties.spring.json.value.default.type=com.LinkedInProject.userService.event.UserCreatedEvent

# Disable Type Headers to ignore producer package structure & Trust all packages
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.session.timeout.ms=45000
spring.kafka.consumer.properties.max.poll.interval.ms=600000
spring.kafka.consumer.properties.heartbeat.interval.ms=3000