spring.application.name=posts-service

server.servlet.context-path=/posts
server.port=9010

spring.datasource.url=jdbc:postgresql://localhost:5432/postsDB
spring.datasource.username=postgres
spring.datasource.password=khushi
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notifications-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Prevent sending producer package type information in headers
spring.kafka.producer.properties.spring.json.add.type.headers=false