eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.kafka.bootstrap-servers=kafka:9092

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://posts-db:5432/postsDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:khushi}

# Hardcoded service URLs to prevent circular Kubernetes env var resolution
USER_SERVICE_URI=http://user-service
POSTS_SERVICE_URI=http://posts-service
CONNECTIONS_SERVICE_URI=http://connections-service
NOTIFICATION_SERVICE_URI=http://notification-service
UPLOADER_SERVICE_URI=http://uploader-service

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect