apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    cloud.google.com/backend-config: '{"default":"api-gateway-backend"}'
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service: 
            name: api-gateway
            port: 
              number: 80

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backend
spec:
  healthCheck:
    requestPath: /actuator/health
    type: HTTP