apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - name: notifications-service
        image: linkedin-app-notifications-service?uuid=8CA2F3D8-1848-4CF8-9DBA-657A8B74E080
        imagePullPolicy: Always
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          requests:
            memory: "350Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: khushi
          - name: DB_SERVER
            value: "notification-db"
          - name: DB_NAME
            value: "notificationDB"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://notification-db:5432/notificationDB"
          - name: SPRING_JPA_DATABASE_PLATFORM
            value: "org.hibernate.dialect.PostgreSQLDialect"
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka.kafka.svc.cluster.local:9092"
        ports:
        - containerPort: 9040

---

apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 8080
    targetPort: 9040