apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-service
spec:
  selector:
    matchLabels:
      app: uploader-service
  template:
    metadata:
      labels:
        app: uploader-service
    spec:
      containers:
      - name: uploader-service
        image: linkedin-app-uploader-service:latest
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: CLOUDINARY_CLOUD_NAME
            value: "xitueple"
          - name: CLOUDINARY_API_KEY
            value: "214731115954721"
          - name: CLOUDINARY_API_SECRET
            value: "mHfTD7Mm72MRym7lcbnoQ__c_LI"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/gcp-credentials.json
        volumeMounts:
          - name: gcp-key-volume
            mountPath: /var/secrets/google
            readOnly: true
        ports:
        - containerPort: 9050
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: cloudinary-gcp-creds

---

apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: uploader-service
  ports:
  - port: 8080
    targetPort: 9050