spring.application.name=uploader-service
server.servlet.context-path=/uploads
server.port=9050
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# GCP Service Account Key Configuration
# GCP Service Account Key & Storage Configuration
spring.cloud.gcp.credentials.location=classpath:gcp-key.json
gcp.bucket.name=p2-cs-linkedinclone