spring.application.name=user-service

server.port=9020
server.servlet.context-path=/users

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=khushi
spring.jpa.hibernate.ddl-auto=update

# Security
jwt.secretKey=iloveyoukhushiiloveyousomuchiloveyouiloveyouiloveyouyouaremyeverythinglpgo4k[plv'lmberokgmietbonryojneoimgrtbmm

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Kafka Producer Configuration (matching posts-service)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Disable sending producer package type information in headers
spring.kafka.producer.properties.spring.json.add.type.headers=false