eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.datasource.url=jdbc:postgresql://${DB_SERVER:user-db}:5432/${DB_NAME:userDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:khushi}

USER_SERVICE_URI=${USER_SERVICE_URI:http://user-service}
POSTS_SERVICE_URI=${POSTS_SERVICE_URI:http://posts-service}
CONNECTIONS_SERVICE_URI=${CONNECTIONS_SERVICE_URI:http://connections-service}
NOTIFICATION_SERVICE_URI=${NOTIFICATION_SERVICE_URI:http://notification-service}
UPLOADER_SERVICE_URI=${UPLOADER_SERVICE_URI:http://uploader-service}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect