spring.datasource.url=${DB_URL:jdbc:postgresql://${DB_SERVER:notification-db}:5432/${DB_NAME:notificationDB}}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:khushi}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.kafka.bootstrap-servers=kafka:9092